name: Build project after push

on: issue_comment: types: [created, edited]

workflow_dispatch:

jobs: build: if: github.event.issue.pull_request == null && github.event.issue.number == 1 runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'temurin'
      cache: gradle

  - name: Grant execute permission for gradlew
    run: chmod +x gradlew

  - name: Build with Gradle
    run: ./gradlew build

  - name: Build debug APK
    run: ./gradlew assembleDebug --stacktrace

  - name: Check generated files
    run: ls -al app/build/outputs/apk/debug

  - name: Upload Debug APK as Artifact
    uses: actions/upload-artifact@v3
    with:
      name: debug-apk
      path: app/build/outputs/apk/debug/app-debug.apk

  - name: Create GitHub Release
    uses: softprops/action-gh-release@v1
    with:
      tag_name: v${{ github.run_number }}
      name: Release v${{ github.run_number }}
      files: app/build/outputs/apk/debug/app-debug.apk
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

