name: Build Apk Release Android Project

on:
     workflow_dispatch:
     
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Gradle Wrapper Permission
        run: chmod +x gradlew

      - name: Build Project with Gradle
        run: ./gradlew build --stacktrace

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Verify APK Output
        run: |
          ls -al app/build/outputs/apk/debug/
          if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "Error: APK file not found!"
            exit 1
          else
            echo "APK found, size:"
            du -h app/build/outputs/apk/debug/app-debug.apk
          fi

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ github.event.repository.name }}.apk
          ls -al app/build/outputs/apk/debug/

      - name: Create GitHub Release
        if: success()
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          files: ./app/build/outputs/apk/debug/${{ github.event.repository.name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
